<a href="https://colab.research.google.com/github/SonalDhoke/Assessment_Programming_with_Data_Analysis/blob/main/PDA_Assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing the necessary libraries for data analysis
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
drive_path ='/content/drive/MyDrive/Colab/Programming_DA/PDA_Assessment/Assessment Data-20251118'

In [5]:
dataframes = []
for filename in os.listdir(drive_path):
    if filename.endswith('.csv'):  # Check if the file is a CSV file
        file_path = os.path.join(drive_path, filename)
        df = pd.read_csv(file_path)  # Read the CSV file into a DataFrame
        dataframes.append(df)  # Add the DataFrame to the list

In [6]:
df = pd.concat(dataframes, ignore_index=True)
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Brajrajnagar,07/12/2017,171.38,311.68,NaN,41.07,NaN,7.78,3.26,5.83,4.69,0.00,NaN,NaN,NaN,NaN
1,Brajrajnagar,08/12/2017,126.67,192.81,NaN,20.16,NaN,7.97,2.94,5.43,10.51,0.00,NaN,NaN,304.0,Very Poor
2,Brajrajnagar,09/12/2017,105.11,154.39,NaN,18.40,NaN,8.15,2.83,5.10,10.33,0.00,NaN,NaN,291.0,Poor
3,Brajrajnagar,10/12/2017,65.25,99.73,NaN,15.21,NaN,7.90,2.74,4.75,8.37,0.00,NaN,NaN,189.0,Moderate
4,Brajrajnagar,11/12/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Ahmedabad,27/06/2020,62.12,118.67,9.18,56.35,19.86,NaN,0.49,12.44,68.05,1.32,37.76,1.62,92.0,Satisfactory
29527,Ahmedabad,28/06/2020,31.57,NaN,6.37,23.99,16.40,NaN,0.52,11.01,26.34,1.37,49.58,1.34,82.0,Satisfactory
29528,Ahmedabad,29/06/2020,29.75,127.98,9.06,25.15,18.92,NaN,0.67,12.10,34.99,1.39,60.21,0.79,74.0,Satisfactory
29529,Ahmedabad,30/06/2020,40.02,121.10,7.09,58.92,33.41,NaN,0.73,16.39,41.64,1.21,44.10,1.35,98.0,Satisfactory
29530,Ahmedabad,01/07/2020,37.63,NaN,4.42,35.04,20.17,NaN,0.28,14.40,9.69,1.73,47.05,1.87,119.0,Moderate

In [7]:
df.to_csv('Assessment_Data_combined.csv', index=False)

In [8]:
print(f"The Data has {df.shape[0]} total records and {df.shape[1]} columns ")

The Data has 29531 total records and 16 columns

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [10]:
df.duplicated().sum() #checking for duplicate records
duplicate_row=df[df.duplicated()]
print (duplicate_row)

Empty DataFrame
Columns: [City, Date, PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, Xylene, AQI, AQI_Bucket]
Index: []

In [17]:
cols = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3',
        'Benzene','Toluene','Xylene','AQI','AQI_Bucket']

blank_rows_count = df[cols].isna().all(axis=1).sum()

print("Number of rows with all columns blank:", blank_rows_count)

Number of rows with all columns blank: 0

In [16]:
cols = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3',
        'Benzene','Toluene','Xylene','AQI','AQI_Bucket']

df = df[~df[cols].isna().all(axis=1)]

In [20]:
def missing_values_table(df):
    # Total missing values
    mis_val = df.isnull().sum()

    # Percentage of missing values
    mis_val_percent = 100 * mis_val / len(df)

    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)

    mis_val_table = mis_val_table.rename(columns={0: 'Missing Values', 1: '% of Total Values'})

    # Sort the table by percentage of missing descending
    mis_val_table = mis_val_table.sort_values('% of Total Values', ascending=False)

    return mis_val_table

missing_values = missing_values_table(df)
display(missing_values.style.background_gradient(cmap='Greens'))